job_levels:
  ds: Data Scientist
  sds: Senior DS
  pds: Principal DS
  eds: Expert DS
eoy_rating_levels:
  - Needs improvement
  - Adequate
  - Superstar
valid_colours:
  - teal
  - lightblue
  - teal
  - lightblue
  - teal
  - lightblue
  - teal
  - lightblue
  - teal
  - teal
  # Above will alternate the colours :) below are some valid colours
  # - lightblue
  # - navy
  # - purple
  # - fuchsia
  # - pink
  # - orange
  # - lime
  # - indigo

