job_levels:
  ds: Data Scientist
  sds: Senior DS
  pds: Principal DS
  eds: Expert DS
draft_eoy_rating:
  - Needs improvement
  - Adequate
  - Superstar
valid_colours:
  - teal
  - lightblue
  - navy
  - purple
  - fuchsia
  - pink
  - orange
  - lime
  - indigo
